### PR TITLE
Create be-BY.json

### PR DESCRIPTION
**Pull request by Gazmanovich**

### CODE REVIEW

**Comment by cph101** [comment]
Hi, and thanks for contributing! Myself and @jmarcinik3 have agreed to start working on a new version. I’ve invited Cal to the repo, and he’s joined, so I’ll transfer ownership once it’s working. 

*The reason I say this is because he appears not to be active on this repo’s issue and pull req tracker, so it’s more likely to get merged into a public version if you add it to [the v2 repo](https://github.com/cph101/enchant-order-v2).*

**Comment by iamcal** [comment]
merged, thank you

**Comment by Gazmanovich** [comment]
Name of language is Беларуская, not Беларускі. Plz, fix

**Comment by iamcal** [comment]
I have made this change

**Pull request merged**
