### PR TITLE
Feat: Add german translations

### PR DESCRIPTION
**Pull request by quentinberry**
# What?

Add german translation.

# How was it tested?

Not tested yet, because I dont know how to run this project, except for the `index.html`. I would gladly love to know how to start locally :D

# German ressources

I am a german boy. So as I love to use this tool, I wanted to add my part to it. I am currently working as a Frontend Engineer at an online fashion retailer where I also have to speak english for my day-to-day bread.

I cross-checked the enchantment names with the wiki, so I dont get anything wrong.

### CODE REVIEW

**Comment by cph101** [comment]
## Yo this is great! 

I don’t have permissions to merge it, but I can suggest how to run it locally. It really depends on your IDE, though if you can run index.html, the css and other files should automatically get added to the html when requested by the browser.

If, when you run index.html, it doesn’t appear exactly the same as [the published site](https://iamcal.github.io/enchant-order/), please let me know how you’re running it and I can try to offer some more advice.

PS: If you need an IDE, I would advise IntelliJ IDEA (the community edition is free), and when you press the run button on index.html, it opens it in-browser with live updates as well, and the styling as well as JavaScript is all loaded automatically.

**Comment by iamcal** [comment]
This PR includes changes to all the whitespace/indentation in script.js - I won’t merge that part, but the German language file is great!

For the language dropdown, it should say “Deutsch” rather than “German”. I’ll make these changes and merge late today

**Comment by quentinberry** [comment]
Good catch, and sorry about that. I forgot to disable my linter. I fixed the whitespaces and Dropdown naming in the recent commit 😄

**Comment by iamcal** [comment]
Merged - thank you!

**Pull request merged**
