### PR TITLE
Edited CSS and added Dutch language configuration

### PR DESCRIPTION
**Pull request by cph101**
Made CSS consistent and fixed a minor alignment error with the level selection buttons.

Thoroughly tested in the latest version of Safari, Safari mobile, and Chromium

### CODE REVIEW

**Comment by cph101** [comment]
I think this might create a bug with the language selection. I’ll just quickly review this to make sure it doesn’t.

**Comment by cph101** [comment]
All good! Seems it was an issue with the lang file I created, not on this pull.

**Comment by iamcal** [comment]
Great set of changes, thank you! I had been meaning to add localstorage for language preference, but had forgotten.

**Comment by cph101** [comment]
I just feel a little bad when I accumulate so many commits and comments on one pull request. Glad to hear you liked them :)

**Comment by iamcal** [comment]
Very happy to be getting contributions to the code!

**Pull request merged**
